import React from "react";
import "./Floor.css";

const Floor = () => {
    return (
      <div id="floorDiv" className="floorDiv">
            <pre className="floor">
                {String.raw`
                    
                                                                                                                                                                                                                                                                                                                                                          '-/+syhdmNNNNNmmdys+/.                                                                                                                                        
                                                                                                                                                 '''''                                                                                                                     '.-:/++ooooo++/:-.'                                                   '-+ymMMMNmhysoo+++oosyhmNMMNds:'                         '-://-'                                                                                                   
                                                                                                                                        .:+shdmNNMMMMMNNmdys+:.                                                                                                      .:+ydNMMMMNNmmmmmmNNMMMMMNdyo/-'         ':+syhhyso:.                    '+hNMMdy+:.''             ''./shNMNh+'                   :sdMMMMMMMmo.      '..-:::::-..'       .:/osyhdmNNNNNNmdys+:.          '-/+syhddhyyso+:-'                    
                        ''.-:://:-.'                '.-://////::-.'                                ./osss+/.                        .+ymMMNmhys++/////+osyhmNMMNho/'                                                                                             ./ymMMNdyo+:-''''''''''''.-:/oyhmMMNmy/-  '+hNMMmhhyhmNMNd+'               :yNMNy/.'''''''''''''''''''''''''''/yNMNy:      .:oyhhhyssmMMho:.''-omMNs./sdmNMMMMMMMMMMMNNmhsydNMMMNdhysoo++++osyhmNMMmy:   ./sdNMMNmdhyyyhddmNMMNds/'                
                   -/shmNNNMMMMMMMNNmhs/-      ./shmNNMMMNNNNNMMMNNmdyo/-' .-:/+ossssssoo+/:.    /dNMNdhdNMNms-                  -omNMmy+-'''             '''-/shNMNd+.                                                            '....''                    -odNMmy+-''                       ''.:oymMNmymMNy/.''  ''':yNMm/            :dMMh/.''''''''''''''''''''''''''''''''./hMMd/  /dNMNdhydMMMmo.'       '+NMNMNhso/::--.--:ohMMMMMmyo/-.''''         ''''-+hMMy/hNMNho/-'''''''''''.-/shNMNh/              
               ':ymNMNdyo/:--....:/oydNMNmy:'.yNMmhs+/-.'''''''.-/+sydmMNNNNNMMNmdddddddmNMMNmh+dMNy-'''''-odMNddmNNNmho:'    '/dNMdo-'''''''''''''''''''''''''''.:smMNh/                       .-:::-.                       -+ydNNNNNNNNmdyo:.           .+dNMds:''''''''''''''''''''''''''''''''''''-oMMMy.'          '.hMMhhddddhs+-'sMMh:......................................:hMMhhMMy/-..oNMm+'            -mMM+--------/ohNNMmho:.''''''''''''''''''''''''''oMMMMy/..''''''''''''''''''../hMMd/            
             '+mMMdo:.''''''''''''''''.:odMMmNMm/.'''''''''''''''''''''.:oymMMMmy+-.......-:+yMMMd-         '-yNMMdooydNMNs.'+mMNy:.''''''''''''''''''''''''''''''''.:yNMm/                 ./ymNNMMMNNNho-                 /dNMdyo+/:::/+sydNMNms:      -sNMms:''''''''''''''''''''''''''''''''''''''''yMM+'''''''''''''/yNMNdysssyhmMNNMMo-........................................./mMMMs:::/dMMs.'''''''''''''''.mMNo///+sdNMMmy+:..''''''''''''''''''''''''''''':MMm/..........................:hMMy'          
            :mMNy:........................:yMMM/'''''''''''''''''''''''''''.-/sdNMNmy+:------oMMh'            '-yMMh:.--omMmmMNs-......................................:hMMy.-/syddddhs+:'.sNMmy+:---:+sdMNd/              yMMy-.''''''''''''.:ohNMm+' -yNMd+.''''''''''''''''''''''''''''''.:+yhdmmdy++MMy.''''''''''':dMMh/.'''''''.-+hMMd+------------------------------------------:hMMhooyNMm:'''''''''''''''''':MMMmhmNMNho:-..................................yMMs----------------------------:yMMy          
           :NMm/----------------------------yMM+................................-/sdNMNdyo+oyMMd.''''''''''''''''/mMNs///oMMMh:.........................................-oMMNNNmhyssyhdNNmNMm+.         '-yMMh.           oMMo.'''''''''''''''''.-sNMmyNMd+...............................:smNMmhyssymMMMM:...........oNMd:.''''''''''''.:hMMy:::::::::::::::::::::::::::::::::::::::::::dMMddMMh-''''''''''''''''''''yMMMMMdo:-------------------------------------oMMMNs/////////////////////////////dMM-         
          'mMN/:::::::::::::::::::::::::::::hMMm:..................................-:+hNMNNNMMN-''''''''''''''''''.yMMdoodMMy-------------------------------------------+dMMh+-.''''''.-+hMMd-''''''''''''':NMmoyhhys+:. 'NMm-.....................:hMMMo-..............................-sNMmo-.'''''.hMMm.........../MMd------------------sMMdyyysso+/::::::::::::::::::::::::::::::::::/NMMMMy......................:MMMNo::::::::::::::::::::::::::::::::::::::/yMMmmMMNho++++++++++++++++++++++++++yMM+         
          /MMh///////////////////////////oymMMNMm/------------------------------------:/smMMMMs.....................oMMmmMMh:::::::::::::::::::::::::::::::::::::::::::yMMh/.''''''''''''./dMN+'''''''''''''oMMNdhhhdNMNhoMMh://++oooooo++//:::-----:mMM:------------------------------:dMMs-........./MMh-----------hMM+:::::::::::::::::::yMMNdmmNMNNmyo/////////////////////////+ooo+//hMMMy-.......................mMMo/////////////////////////////////////+ymMMMNNMMMMNmhsooooooooooooooooooooooodMM/         
          /MMhoooooooooooooooooooooooooydNMMMmmMMNs/:::::::::::::::::::::::::::::::::::::/dMMM-......................oMMMMm///////////////////////////////////+oosyyhhdMMs-................:dMN:...........:NMd-.'''.-/yNMMMNmNNNNNNNNNNNNNNNmmdyso+/yMMo------------------------------dMMo:::::::::::oMMh:::::::::::hMMo///////////////////+NMN....-/sdMNds++++++++++++++++++++oymNNNNNmydMMh-------------------------yMMs++++++++++++++++++++++++++++++++++oydNMMMds+::/ohNMMNdhyyyyyyyyyyyyyyyyyyyyhMMd'         
          .NMNysssssssssssssssssssssydNMMMmdhhdNMMMmyo+///////////////////////////////////oMMd.......................-oMMMh/+ossso+///////////////////////+ohmNNNmmddNMMy:::::::::::::::::::+MMy...........sMM/.........:hMMMyo/:--------::+oshdmNMNNNMMs:::::::::::::::::::::::::::::oMMd++++++++++++mMMh///////////sMMdoooooooooooooooooooomMN.''''''./dMNyooooooooooooooooosdNMmy/::smMMMm:-------------------------sMMyooooooooooooooooooooooooooooooooymNMMMMd+-.......:mMMMMmdhhhhhhhhhhhhhhhhdmMMd.          
           /NMNhhhhhhhhhhhhhhhhhhhdmMMMMy:-.''.-+dMMMNmhso++++++++++++++++++++++++++++++++sMMy-------------------------yMMmdNMNNMNNhs++++++++++++++++++++smMNds/-..''NMN+///////////////////+MMh-----------yMM+:::::::::::yMMy.................--:/ohmNMNmyo/:::::::::::::::/+syhhhyyshMMysssssssssssdMMMd++++++++++++hMMdysssssssssssssssssyMMd.........-mMNhyyyssssssssssssdNMm+.'''''.yMMh::::::::::::::::::::::::::yMMhsssssssssssssssssssssssssssssshNMMNmMMh:----------yMMdyhNNNmmmmmmmmmmmmmNMMmo'           
            :dMMNmddddddddddddddmNNNMMMy.........-oNMMNMMmysoooooooooooooooooooooooooooooohMMs::::::::::::::::::::::::::dMMMd/-.-odMMmyooooooooooooooooohMMh:.'''''''MMmoooooooooooooooooooodMMo:::::::::::+MMd++++++++++++dMM+::::::::::::::::::::::/+ohmNMmho////////////smNNmddddmNMMMmdhhhhhhhhdNMMMMMmmdys+++++++ohNMNdhhhhhhhhhhhhhhhdNMN/----------yMMNNMNNmmdhyyyyyhNMNs.''''''''.sMMh/////////////////////////hMMNyyyyyyyyyyyyyyyyyyyyyyyyyyyyhmMMmmNMMm///////////+NMy/::hNmMMMMMMMMMMMMNdy/'             
             '/hNMMMNNNNNNNNNNMMMh//+mMh:::::::::::oNMNMMMMmhsssssssssssssssssssssssssssssdMMs:::::::::::::::::::::::::/mMNo''''''':hMMdsssssssssssyyyhhMMm-.........mMMysssssssssssssssssydMMh/:::::::::::/hMMhsoooooooooohMMy++++++++osssoo++++++++++++oshNMNds+++++++++dMMy:.''''.-/shmMMNmmmNNMMNmdyssyhmMNdsooooooosdNMNNmmddddddddmmNMMd+:::::::::::hMM:-:+shmNMNNmddMMm/............yMMy////////////////////////mMMMNdhhhhhhhhhhhhhhhhhhhhdddddmMMNo/:sMMhoooooooooosmMMmhhdMmhmMMMMMMMMMMMNhs+/-'           
              './smMMMMMMMMMMMmymmsooyMMs+++++++++++dMMdyydMMmhyyyyyyyyyyyyyyyyyyyyyyyyyyhNMMh////////////////////////+mMN+'''''''''.+NMNhyyyyhhdmNNMNNNMMy----------+NMNdhhhhhhhhhhhhhhhdNMNy//////////////+dMMmhyyhhhddddmMMdssssssymNMNNMNmyssssssssssyyhmMMMMmmdhso++hMMs''''''''''''-/ymMMMMmy+-''     '/NMNsssssssssydMMMMMMMNNMMMMMNds+++++++++++++NMd''''''.-/sdNMMMd:--------------dMMs++++++++++++++++++++++oMMhdMMNmddddddddmmmmNNNNNNMMMMMMMMNmmmmMMNhhyyyyyyhdNMMMMMMNmmddhhyyyyyhhyyhdmNMNmy/.        
          .:ohdNNNNNNNNNNNNNNNNNNMMNNMMMMhysssssssssmMM+::/hMMNmddddddddddddddddddddddddmMMMMN+//////////////////////+dMM+............:dMMddmNMNmdyo/:-:MMh:::::::::::+mMMNmmdddddddddmNNMMds++++++++++++++++oMMMMNNNMNNmmmmNMNmmdddNMMd/-:+hMMmdddddddmNMMNmhyssyhdNMNmyNMm................-odMMh:'''''''''''oMMdyyyyyyyyyyMMMMMMMNNmmdhysoooooooooooooomMM/''''''''''.+MMm/:::::::::::::::/NMNoooooooooooooooooooooomMMddMMMMMNNNNNNMMMNmmdhysoo+//////++syhdmNMNNmmmmNNMMMmhs/:-.'''''''''''''''''-:ohNMms.      
        -ymMNds+:--..----.----://oshmNMMMMNddddddddNMMMdyssyNMMMMNNmmmmmmmmmmmmmmmmmmmNMMMyhMMs++++++++++++++++++++++hMMy--------------:dMMMmh+:.'''''''mMN+++++++++++++sdNMMMMMNNMMMMMNMMmooooooooooooooooooyMMMMNds+:-.''.-+dMMMMMMm/'    '+NMMMMMMMMNdo:.'      './yNMMMy-------------------+dMNy-'''''''''-MMmhhhhhhhhhNMMhhdNMNhysssssssssssssssssymMMs............mMNo/////////////////sMMdoooooooooooooooooooohMMdhyyhhdmNMMMMdy+/-.''                 '.:+sdNMMMMMNy/.'''''''''''''''''''''''''''-omMm/     
      .yMMd+-''''''''''''''''''''''''-:ohNMMMMNNNMMNmyMMMMNMMMMMMMMMMMMMMNNNNNNNMMMMMMMMMMNNMMmooooooooooooooooooooosMMd/:::::::::::::::/mMM/'''''''''''+MMdoooooooooooooosyhdmNNMMMMMNmMMNssssssssssssssssydNMmh+-'''''''''''.hMMMmo.''''''''/MMNNMNd+.               -hMMs::::::::::::::::::::/yNMd:........:MMNddddddddmMMs   -dMMmhhhhhhhhhhhhhhhhdNMNo-...........oMMh++++++++++++++++++odMMyssssssssssssssssssyMMd'     '.-+dMMy.'''''''''''''''''''''''''''''-+ymMMd:...............................:dMN/    
     -mMN+...............................:yNMMhyhhmNNMNmmdhyyyyhdmmNNMMMMMMMNNNMMMMNdyo+///+yMMhooooooooooooooooooosNMNo/////////////////oNMm............sMMmysssssssssssssssssyhNMNddhhdMMdyyyyyyyyyyyyyhmMMdo-...............:MMm-'''''''''''sMMNy:'''''''''''''''''''/MMy++++++++++++++++++++++sMMd--------sMMNmmmmmmmNMMy'    'omMMNmmdddddddddmmNMNh/-------------dMMssssssssssssssssssssyMMmssssssssssssssssyhMMd-'''''''''''+NMh.'''''''''''''''''''''''''''''''-+mMN+-------------------------------:NMm'   
    'mMN/----------------------------------oMMysmMNds/-.'''''''''''.-/+ymNMMh:+MMm+.'''''''''hMMhssssssssssssssssssdMMhooooooooooooooooooohMM+------------oNMNdhhhhhhhhhhhhhhhhmMMh.    'mMMhyyyyyyyyyyhmMMd+-------------------dMM-...........-NMm''''''''''''''''''''':MMdooooooooooooooooooooooomMM/::::::/mMMNNNNNNNMMNo''''''''.+hNMMMMMNNNMMMMNNh+:::::::::::::::mMMyyyyyyyyyyyyyyyyyyyyyNMMyyyyyyyyyyyyyyyydMMd-.............sMM+.................................:mMN+///////////////////////////////hMM-   
    /MMy:::::::::::::::::::::::::::::::::::/MMMMmo-.''''''''''''''''''''.:omMNNMd-'''''''''''.hMMdyyyyyyyyyyyyyyyyyNMNssssssssssssssssssssyMMh-------------/dNMNmmmddddddddmmNMMm+'      /MMNhhhhhhhhhdNMNs:::::::::::::::::::::hMM/------------dMM-''''''''''''''''''''.NMNysssssssssssssssssssyydMMd///////yMMMMMMMMMMNy-''''''''''''./oyhdmmNMMNyo++++++++//////////dMMdhhhhhhhhhhhhhhhhhhhmMMmhhhhhhhhhhhhhhhNMMh:--------------/MMy---------------------------::+oyhdNMMNNmmddyo++++++++++++++++++++++++dMM.   
    +MMy++++++++++++++++++++++++++ossyyyyssyMMMM/---------------------------hMMM/.............-hMMmhyyyyyyyyyyyyyyhMMNyyyyyyyyyyyyyyyyyyyyhMMd:::::::::::::::+hNMMMMMMNMMMMMNNh/''''''''''oMMNddddddddMMNo//////////////////////hMM+::::::::::::yMM+.....................sMMmhhhhhhhhhhhhhhhhhdmNMMNho++++++sMMMMMmddhs+-'''''''''''''''''''''.-yMMddmNMNNMNNdho+++++++oNMMmmmmmmmmmmmmmmmmmNMMMNddhhhhhhhhhhhdmMMNs::::::::::::::::+MMh::::::::::::::::::::::::/shmNMNmdhssooosyhmNMmysssssssssssssssssssssyMMd    
    .MMmooooooooooooooooooooooohmNMNNNNNNNNNMMMMho/:::::::::::::::::::::::::/MMN:--------------:sNMNdhhhhhhhhhhhhhhNMMmddhhhhhhhhhhhhhhhhhmMMy/////////+++ooo+++oyNMMmmddhs+:.'''''''''''''oNMMNmmmmmNMMdooooooooooooooooooooooomMM/////////////yMM+.....................-dMMmddddddddddmmmNNMMMNdhsoooooosyMMdsNMd-.............................+NMMh+/::/+ymMMmyoooooosdNMMMMMMNNNMMMMMMMNNmNNMMNmdddddddddmMMNh+////////////////+hMMs/////////////////////+ymMNmyo:-'''''''''''':hMMdyyyyyyyyyyyyyyyyyyyhNMm.    
     sMMdyssssssssssssssssssshNMNy/:.''''.-:/oydNMMmho++////////////////////oMMM+////////////////omMMNddddddddddddddNMMMNNmmmmmmmmmmmmmmmNMMd+++++++osdmNMMNMMNNdmMNs.'''''''''''''''''''''':dMMMMMMMMMMNhyssssssssssssssssssssyMMm+++++++++++++mMM:---------------------:+mMMMNNNNNMMMMMMMNmdhyyyyyyyyyyydMMd. :NMm-............................./NMm.'''''''/dMMdsssssssyhdmNNNMMMNmdhyo/-' '-+yNMMNmmmmmNMMMdsoooooooooooooooooosNMN++++++++++++++++++++sdMMms:.'''''''''''''''''.NMMddddddddddddddddddNMMh.     
      sMMNdhhhhhhhhhhhhhhhhhhNMN-'''''''''''''''./sdNMNhsooooooooooooooooooomMMMh++++++++++++++++++yNMMNmdddddddmNMMNmhydNMMMMMMMMMMMMMMMMNhooooooohNMNho/:-:/+dMMm/........................../ymMMMNs/sNMNmdhhhhhhhhhhhhhhhhhhmMMyoooooooooooosMMd-------------------:sdNMNNNMMMMMMNhsoNMMhhhhhhhhhhhhhdNMMy.'''+MMh------------------------------+MMd.''''''''oMMmyyhhyyyyyyyydMMy''''''''''''''.+mMMNNMMMMmysssssssssssssssssssyNMNsoooooooooooooooooosmMMd+-.....................mMMNNNmmmmmmmmmmNNNMMNd/       
       :dMMNmmmdddddddddddddmMMy....................:smMMmyyyyyyyyyyyyyyyyyNMNmMMyoosssyyyyyysssooooshNMMNNmmmNMMNh+-'   '-/osyhmMMMNmmdhysssssssyNMMs-''''''':NMd:.............................:NMm-   .+hNMMMNmmmdddddddddddmMMmsssssssssssssmMMo::::::::::::::::::sNMms/---/hMMMMy---+NMNddddddddddmNMMd/......hMM/::::::::::::::::::::::::::::::sMMs.........oMMMMMMMNmdhhhhMMm..................yMMMMMMMMdhyyyyyyyyyyyyyyyyhdMMNysssssssssssssssssshMMmo:::::::::::::::::::::::+MMMMMMMMMMMMMMMMMMMm+-         
         :smMMMMMMMMMMMMMMMMMMMd-----------------------sNMMmhhhhhhhhhhhhdmMMm-.NMMmNMMMMMMMMMMMMNNmdhyyNMMMMMMMMs-'''''''''''''''hMMdyyyyyyyhhhhhNMN:''''''''-NMm:------------------------------dMN:'''''''':+ydMMMMMMNNNNNNNMMMmyyhmNMMMMNmdydMMd/:::::::::::::::::sMMh-......-NMMMs----+NMMNNNNNNNNMMMd+-.......+MMy:::::::::::::::::::::::::::::::mMN:-------+mMNh+//sNMMmddmMMs-------------------yMMmyyhMMNmddddddddddddddmMMMMNdhyyyyyyyyyhhhhhhydMMd/////////////////////////mMMMNho+///oyNMMs-dMM/          
           -NMmsdMMMNmdhdmNMMMMMo:::::::::::::::::::::::/hMMNmmmmmmmmmNNMMm+-smMMNhs+/:--..--:/+oydNMMMMMh+dMMm:.................-NMNhhhhdNMMMMMMMM:.........dMM/::::::::::::::::::::::::::::::oMMs.............:mMMMMdNMMMMMNmhhhmMMdo//+smMMMMm///////////////////NMN/////////NMMMy:::::/yNMMMMMMMMmy/----------/MMd///////////////////////////////sMMy::::::+MMd-.....-dMMNNNMMo::::::::::/:::::::::NMm'''-yNMMNNNNNNNNNNNMMMdo+sdMMNdhhhdNMMMMMMMMMMMNo+++++++++++++++++++++++omMMy:.''''''''-mMN..hMM/         
          :NMd..NMm/'''''''-odMMNo++++++++++++++++++++++++hMMMMMMMMMMMMdo--hMMd+-                   ./sdMMNNMN/-------------------dMMdddNMMh/-:+yMMm/-------oMMy:::::::::::::::::::::::::::::::dMM-..............-dMMM+--yMMNdddddMMd.......+NMMo+++++++++++++++++++NMNoooooooodMMMMy////////sMMmhyo/:::::::::::::+MMd///////////////////////////////+NMN//////hMM+:::::::/MMMMMMMy//////ohNMMMms//////dMM......+ymNMMMMMMMNmyo-.....:yMMNmMMNy+:-..-+NMMNsssssssssssssssssssssssyNMN/------------hMM-..dMM:        
         -NMd.'+MMo.........../mMMyooooooooooooooooooooooooMMMMmhyyhmMMNyoMMd:''''''''''''''''''''''''''./hMMh:::::::/oo+:::::::::hMMNNNMMo......:NMN/::::::mMN////////////////////////////////NMN----------------:mMMy:::yMMNmmmmMMd::::::::oMMh+++++++++++++++++++hMMNhyyyyhmMMMMMd++++++++hMMs/////////////////sMMh++++++++++++++++++++++++++++++++mMM++++++hMMy++++++++NMN--MMm++++omMMd+:hMMy+++++NMM----------://///:------------+MMMMh:--------oMMMNhyyyyyyyyyyyyyyyyyyyhmMMMo////////////+NMm...-mMN.       
        .NMm-../MMy::::::::::::/mMMdyyyyyyyyyyyyyyyyyyyyyydMMMo......-+dMMMy''''''''''''''''''''''''''''''/MMy/////+dMMMMMdo/////+mMMMMMMm::::::::yMMs/////+MMd///////////////////////////////+NMN:::::::::::::::::+MMm////omMMMMNMMMs+++++++sMMdooooooooooooooooshmMMNMMMNNNMMNNMMMN++++++++mMMo+++++++++++++++++mMMsoooooooooooooooooooooooooooooooodMMsooooosNMMhyyyyyyhMMh  hMMyoohMMm:''''NMNooooyMMh::::::::::::::::::::::::::::::yMMMo/////////hMMMMMNmdddddddddddddddmNMMMMmoooooooooooosNMMo----/MMh       
        dMN/...-dMMs++++++++++++sMMMMmhhhhhhhhhhhhhhhhhhdNMMMM/:::::::::hMM/'''''''''''''''''''''''''''''':MMd++++omMN/./hMMmsydNMMMMMMMMdoooooooomMMs+++++yMMh++++++++++++++++++++++++++++++++mMM+/////////////////dMMo////+shmMMMMMNhyyyyyhNMMysssssssssssssshmMMms:'-oyddhs/'yMMMMyooooooomMMsoooooooooooooooosMMmsssssssssssssssssssssssssssssssssmMMyyyyyyyymMMNNmmmmMMMMNddMMNydMMy.'''''yMMhyyyNMNo++++++++++++++++++++++++++++++sMMMmysssssssdMMd-+hNMMMNNNNNNNNNNNMMMNh+NMNyyyyyyyyyyhdMMMMN/----yMM/      
       oMMs----/NMMMdsssssssssssyMMNmMMNmmmmmmmmmmmmmmNMMMMMMMhooooooooodMM/...............................mMMssssyMMs'''':mMMMNy+:-..-NMNyyyyyyhmMMdoooooohMMyoooooooooooooooooooooooooooooooohMMy+++++++++++++++++yMMy+++++++oMMMMNMMNmmmNMMMMmdysssssssssydNMNy:'''''''''''''hMMMMNsssssssdMMdssssssssssssssssmMMNdysssssssssssssssssssssssssssssssNMMhhhhhhhhhmMMNMMMNdo/+oyhNMMNMMy.......sMMdhdMMNysoooooooooooooooooooooooooooooohMMNMMNmmmmNMMMy:---:+shmMMMMMMMMNmdy+-..oMMNmddddmmmNMMms/MMd::::/NMm'     
      .NMm:::::mMNyNMNmdhhhhhhhhmMMo.+ymMMMMMMMMMMMMMMmh+::/yMMmhyyyyyhmMMy--------------------------------/NMNyyymMM:'''':mMN+'       /NMMNmmNNMMNdyyyyyyydMMhsssssssssssssssssssssssssssssssssMMmooooooooooooooooohMMyooooooohMMMM//ymNMNdy//ymMMNdyyyyyydNMNs-''''''''''''''-NMh+MMdyyyyyymMMMhyyyyyyyyyyyyyydMMNMMMmhyyyyyyyyyyyyyyyyyyyyyyyyyyyyhMMNdddmNNMMMMMh''..''     '':mMMd--------sMMNNMMMMMMMMNmdhyyyyyyyyyyyyyyyyyyyyyyyyNMN/sdNMMMMNds/:::::::::hMMMd///:---------+hNMMMMMMMNdy+---hMM+////yMM+     
      yMMo////sMMs-:sdMMMMNNNNNMMNs-..--:+smMMmhhyso/-.......+dMMMNNNMMMMMs---------------------------------+NMMdhNMM:.../NMm-         '.sdmNNmMMMdhhhhhhhhdMMdsssssssssssssssssssssssssssssssydMMMhssssssssssssssssmMMmddddhhyMMMMM/'''...'''''':yNMNmhhhmMMh:................sMM:/MMMdyyyyyNMMMMmdhhhhhhhhhhhmMMMMMMMMMNhhhhhhhhhhhhhhhhhhhhhhhhhhhmMMNNNNMMdo+sNMm.'''''''''''''hMM+::::::::hMMMMMMhs+++oshNMMNdhhhhhhhhhhhhhhhhhhhdNMNo/////++/////////////+NMMs:::::::::::::::::+osso+/:::::::oMMy+++++NMm     
     .NMm/////mMM:---:/oyhddmddho:--------/MMd:----------------/oyhddhsoMMd::::::::::::::::::::::::::::::::::/hMMNMMM/--/NMm.''''''''''''''....yMMMMMMNNddddMMNyyyyyyyyyyyyyyyyyyyyyyyyyyyyydNMMNMMNhyyyyyyyyyyyyyydMMMmdddmNMMMMmMMy''''''''''''''-sNMMmNMNo-................/MMdyMMdMMmhhhdMMmmMMNmmmmmmmmmmNMMh-:yMMdmMMmhhhhhhhhhhhhhhhhhhhhhhhhmMMMMMMMMy----+MMy''''''''''''-MMm/////////NMNNMN:.''''''../hMMNNNNNmmmmmmmmmmNNNNMMdo////////////////////oNMNo/:::::::::::::::::::::::::::::::+MMd+++++dMM-    
     +MMy+++++NMm::::::::::///::::::::::::hMMo::::::::::::::::::::///:::dMM+///////////////////////////////////+hmMMMo:/mMN:'''''''''''''''''''oMMd+/omMMNNNMMMdhhhhhhhhhhhhhhhhhhhhhhhhhhdNMMMMMMMMNdhhhhhhhhhhhhmMMMMo'''''./sdMMMN-...............-yMMMN/-------:+osssso+/+NMmmMN+'sMMNddmMMdyhmMMMMNNNNNMMMNs----NMN/hMMNdddddddmmNNNNNmmddddddmMMdsoohMMh+++++NMm''''''''''''+MMhoooooooosMMyNMd------------+NMMMMMMMMMMMMMMMMMNmds+++++++++++++++++++++oNMNo///////////////////////+osyyso+//oMMdoooooyMM+    
     dMMooooooMMm/////////////////////////dMMo++++++++++++++++++++++++++sMMm+////////////////////////////////////+yMMh+dMM+...................-MMm:---:mMMMMMMMMdhhhhhhhhhhhhhhhhhhhhhhhdNMMdNMNo:/NMNmmmmmmmmmmmNMMmMMh        '.oMMh-...............-/mMNo:::::/hNNMNmmmNMNMMMdMM+'''+NMMmNMMhhhhdNMMMMMMMMMMmyo///NMN++dMMNmmmNNMMNdhhhdmMMNNmmNMMy'   'hMMdhhhdMMh............sMMhsssssssymMMomMM+////////////oMMNssssyyyyyyysssoooooooooooooooooooooooosNMNs++++++++++++++++++++++sdNMMNNNMNNddMMhsssssyMMy    
     MMNssssssNMNoshdNNNNmdyo+++++++++++++hMMhoooooooooooooooooooooooooosdMMh+++++++++++++++++++++++++++++++++++++oNMNyMMy....................+MMh++++oNMNo++oNMNmdddddmmNNNNNNmmdddddddMMNsoMMy.../dMMMNNNNNNMMMMmhyNMN'         'oMMy-----------------:dMMy///+NMm+..''..-/shNMMN/.'''-hMMMMNddNMMNdys+////+shNMNhdMMhoodMMMMMMMms:.'''''.:yNMMMMm+''''''.odMMMMMMh:............sMMdyyhdmNNNMMMNMMMNdysoooooooooomMMsssssssssssssssssydmNNNNmdhyyhhdmmmmmdNMMhsoooooooooooooooooooosmMMh+....:ohNMMMhyyyyyyMMy    
    'MMmssssssmMMNMNhso+oymMNdoooooooooooooNMNhyyyyyyyyyhhhhhhhyyyyyyhhhhhNMMhooooooooooooooooooooooooooooooooooooodMMMMm---------------------:NMNhhhdNMN/    :mMMNmmNMMNdhhhdmNMMNNmmNMMMs+sMMh//+ohNMMMMMMMMMMNdhhhmMM/'''''''''''sMMh/:::::::::::::::::hMMh++mMN-'''''''''''./hNMmo..../mMMNNMMd+-'''''''''''.oNMMMmyhmMMdhMMd/.''''''''''':mMMy.'''''''''.:dMMs/:-------------+MMNmNMMmhs+:-..-:+ymMNmhyyyyyyyyNMMysyyyyyyyysssssymMMdyssshNMMMMmdhhhhhddNMMNNdhyssssssssssssssshNMm:'       '.omMMmhhhhhMMs    
    'MMmyyyyydNMNh/.'     .+mMNyoooooooooooyNMMmdddmmNNNMMMMMMMNNNmNNMMNNMMMMMdsssssssssssssssssssssssssssssssssssssNMMM+----------------------+mMMMMMmy:''''''.sNMMMMd+-.''''.-+hNMMMMMMMsosNMNydNMmhyo+++oshdNMMNmddMMy''''''''''''+NMmo/////////////////hMMhoMMh''''''''''''''.:yNMd/...yMMMMd/.''''''''''''''':NMMNNMNdsdMMs-..............:NMm-...........+MMy:::::::::::::::/NMMMdo:.'          ./hMMNddddddNMMMmNNNNNNNNNNNmmdmMMs-....sMMdo-.'''''''..-/shNMNmhyyyyyyyyyyyydMMh.            .omMNmhhmMM/    
     NMNhhhdNMNs-'          .hMMdsssssssssssymMMMMMMmdyo+/:::/+oymMMMh/--:/yMMMNhyyhhhhhhhhhhyyyssssssssssssssssssssdMMh::::::::::::::::::::::::/MMMM+-.''''''''.:NMMs.'''''''''''-yNMNyNMNdyhNMMMd/.'       '.-+hNMNmMMN.............:dMMy+///////////////+dMMdMMy................./mMN+--sMMMs-..................sMMNdyo+yMMs-----------------sMMo-----------:MMm/////////////+yNMms:'                '/mMMMMMMMMMNmhyo++//+oosyhdmNMMmyo/:hMMo.''''''''''''''''-+hNMNdhhhhhhhhhdMMd.'''''''''''''''.yMMNmMMm'    
     sMMmdNMMh-'''''''''''''''yMMdyyyyyyyyyyhmMMNh+:.''''''''''''.:hMMy----/mMMMMNMMMNNNNNNNMMNNmdhyyyyyyyyyyyyyyyyyNMM+////////////////////////oMMMm............oMMs.............../mMNshNMMNNMMh.''''''''''''''':yMMMMM-.............-yMMh++++++++++++++++omMMMMd------------------:mMN+-yMMs--------------------+MMh++++NMN/:::::::::::::::::+MMh::::::::::::mMN///////////+yNMmo.'''''''''''''''''''''.hMMMMMmy/-.'''''''''''''..-/sdNMNdMMy...................../hMMmdhhhhhhdNMN-''''''''''''''''''/mMMMN:     
     .mMMMMN+'''''''''''''''''.dMMdhhhhhhhhmMMmo-.'''''''''''''''''.sMMyoymNMNdhso/:---..---:+shmNMNmdhhhhhhhhhhhhhdMMd/////////////////////////dMMMy------------NMN:----------------/NMN++shmMMN-..................+NMMM:---------------yMMhooooooooooooooosyMMMMM/::::::::::::::::::+NMm/NMm:::::::::::::::::::::oMMhooosMMd++++++++++++++++++sMMh////////////mMM+ooo++++++smMNs-''''''''''''''''''''''''.hMMN/-.......................:sNMMM+-----------------------yMMmddddddmMMo'''''''''''''''''''':dMMs      
      -NMMd-''''''''''''''''''':MMNdddddddNMMy:.....................-NMMNMms/-.'''''''''''''''''.:odMMNddddddddddddNMMs++++++++++++++++++++++++yMMMMo:::::::::::/MMd::::::::::::::::::sMMy+++oMMm--------------------/NMN:---------------:dMMysssssssssssshmNNMMMMMd///////////////////dMMyMMy/////////////////////hMMyssssMMNoooooooooooooooooomMMo++++++++++++mMMmNNNmhoooyNMm/.''''''''''''''''''''''''''.dMN/--------------------------+NMMo:::::::::::::::::::::::/NMMNNNNNNMMM/+osyyyso+:-..........-hMN/     
      oMMy-............-:::::--.hMMmmmmmmNMMh::::::::::::::::::::::::dMMNo-........................-+MMNmmmmmmmmmmNMMMooooooooooooooooooooooooyMMMMMo///////////+MMm++++++++++++++++++oMMdooooMMm:::::::::::::::::::::sMMs::::::::::::::::+NMNyyyyyyyyyyhNMNy++hNMMMy++++++++++++++++++hMMdMMh++++++++++++++++++++oNMNyssssdMMdsssssssssssssssydMMdoooooooooooooNMMmyosNMmshMMd-............................./MMd:::::::::::::::::::::::::::mMMh////////////////////////NMMMMMMMMMMMMMNmddddmNNms:.........-dMN:    
     oMMy-.........-+ydmNNNNNNmdmMMMMMMMMMMMs////////////////////////NMMs---------------------------:NMMNNNNNMMMMMMMMNooooooooooooooooooooooydMMMMMMs++++++++++++dMMyoooooooooooooooooyMMdssssNMM+////////////////////+MMm:::::::::::::::::hMMdhhhhhhhhhNMm:    :dMMMyooooooooooooooooodMMyMMmooooooooooooooooooosmMMdyyyyyhNMMmhhhhhhhhhhhhhhNMMMNhsssssssssssyMMM+:::sMMmMMd-...............................hMMs+++++++++++++++++++++++++oNMMMsooooooooooooooooooooooyMMMNdysooshmNMNs. ''.-omMNo---------:mMN-   
    /MMh----------+mMNho/:::/yMMMNNmmmNMMMMMy+++++++++++++++++++++++sMMMo///////////////////////////yMMMMMMNmdhssooMMmssssssssssssssssssssymMMdohMMMhoooooooooooosMMNysssssssssssssssyNMMyssssdMMh+++++++++++++++++++++MMm/////////////////oMMNdhhhhhhdNMN-''''''.hMMMhssssssssssssssssNMModMMdyyyyyyyyyyyyyyyyyymMMmhhhhhhhhmMMNmdddddddddmNMMd+hMMdyyyyyyyyyyNMMMhsssyMMMMN:--------------------------------+MMNhsoooooooooooooooooooooosmMMNMNysssssssssssssssssssymMNh/.'      '-omMm+..---:dMM+---------/NMd'  
   -NMd:---------sMMh-'''''/dMNh+:....-:+hNMNhsoooooooooooooooooooosNMMMdo++++++++++++++++++++++++odMMMMh+:-.''''''MMNyyyyyyyyyyyyyyyyyyymMMNs/::dMMmsssssssssssymMMMMdhhhhhhhhhhhhhdNMMdyyyyyyNMMyoooooooooooooooooooyMMd++++++++++++++++++hMMNmdddddmMMs''''''''.dMMMmhyyyyyyyyyyyyydMMdosmMMmhhhhhhhhhhhhhhhhNMMmdddddddddddNMMMMNNNNNNMMNdo-..sMMmhhhhhhhhmMMNMMNNNNMMMMo::::::::::::::::::::::::::::::::::MMMMNdyyyyyyyyyyyyyyyyyyyyhNMMhsNMMdhyyyyyyyyyyyyyyyydMMm/'''''''''''''-dMMmmNNNmNMMm+:::::::::sMMo  
  'dMN/:::::::::+MMNsyyysoyMMh-           .oNMNhyyyyyyyyyyyyyyyyyyhNMNdMMdssssssssssssssssssssssshNMNNMMs-''''''''.NMNyyhhdddddddhhyyyydMMMMmsssyNMMMdyyyyyyyyyhNMm+yNMNmdddddddddmNMMNdhhhhhhhdMMNysssssssssssssssssyNMNo+++++++++++++++++++yNMMNNNNNNMM/'''''''''-NMMMMmddhhhhhhhhddMMMysssdNMMmddddddddddddmMMMMNmmmmmmmmmmmmMMmdmNNNmmhs/------sMMmddddddNMMNNMNdyyhmMMm:::::::::::::::::::::::::::::::::::NMMMMMMNmddddddddddddddddNMMNhyyymMMNmddddddddddddddmMMm-''''''''''''-smMNdyo///+shmMNds////////mMN' 
  +MMy:::::::/+hNMMNmdddmmNMMy:.'''''''''''':mMMdhhhhhhhhhhhhhhhdmMMNysdMMNdhyyyyyyyyyyyyyyyyhhmNMMNNMNNMNs-.......hMMmNNMNNmmmNNMNmhhmMMmNMMNNNMMmmMMdhhhhhhhdMMd-../yNMMMNNNNNNMMMMmddddddddddmMMNdhhhhhhhhhhhhhhhdNMNyoooooooooooooooooooooyMMMMMMMMMM:..........hMMdNMMNmmmmmmmmNMMMMNhyyyydNMMNNNNNNNNNNMMmsyNMMNNNNNNNNNNMMM+::///::::::::::::dMMNNNNNMMMMMMd:''''+MMy///////////////////////////////////NMMMMMMMMMMNNNNNNNNNNNNMMMMNmmmmmmmNMMMMNNNNNMMMMMNMMMM/'''''''''''.sNMm+-'''''''''./yNMms//////yMM+ 
  mMN///////odMNdo:.'' ''.-+hNMd/.''''''''''':MMMNmmmNmmmmmmmmmNMMNmhhhhdNMMNmmdddddddddddmmNNMMMMMMNh/-oNMm/::::::oMMMNy+:-.'..:oNMMmMMMMNdyooymMNhNMMmdddddmMMm:-----:+ydmNNNNmdMMNmmmmmmmmmmmmMMMMNdddddddddddddNMMNyssssssssssssssssssshmNMNNmmNNMMMM/..........oMM/-hMMMMMMMMMMMMMNMMMNmmdhhdmNMMMMMMMNmho---/ymNMMMMMMMMMMMM+/////////////////+MMMMMMMMMNMMN-.....yMMo//////////////////////////////////+MMMMMMMMMMMMMMMMMMMMNmmmmmmNNNNNNNNMMMMMMMNmyo+/+smMMMd...........-dMNs...............:hMMh++++++MMd 
 :MMh++++++dMMh/''''''''''''':hMMy............yMMMMNNmmNNMMMMMMMMMNNNNNNNNMMMMMMMMNNNNMMMMMMMMMNNmho:----/NMm/////+mMNs-..........+MMMMMmo-'''''.oNMmhMMNNNNNMMN/:::::::::::://:::NMMNNNNNNNNNNNMMmomMMNNNNNNNNNNNMMNhssssssssssssssssssydNMNh+:.''.-/hMMo----------oMMo..oNMMmNMMMMNmhyssyhdNNMNmdhddMMNo+/:-------:+oyhdmmdhydMMs++++++++++++++++++dMMMMMMMMMMMd::::::dMMo++++++++++++++++++++++++++++++++++sMMh+osyddmmmmmmmMMMh:........--:::///yMMNy:.''''''.dMMy-----------yMMo------------------sMMdooooomMN'
 sMMs++++omMNo.................oMMy...........+MMMh:.''.-+yNMMMNNmmmdddhhhyyyMMNhdmmmmmddddhhyso/:::::::::yMMy+++oNMN+::::::::::::oMMMMy:---------yMM/+NMMMMMMMy//////////////////dMMMMMMMMMMMMNdo-.-+hNNMMMMMMMMNmhyyhdmmmmmmdhhyyyyyyhNMNs-'''''''''.MMd::::::::::+MMs---oMMdNMms/.''''''''.:smMMNddMMN::::::::::::::::::::::+MMdooooooooooooooooooyMMd+++smMMMNo+++++mMMooooooooooooooooooooooooooooooooooodMM:''''''''''''hMMo.................+NMm/----------sMMs----------:NMN::::::::::::::::::::hMMyoooodMM.
 hMMooooomMM+:::::::::::::::::::dMM/----------:MMN.........-sNMm+////////////MMm++++++++++++++++++++++++++sMMdsssdMMy+++++++++++++NMMMh/::::::::::sMMdhNMMMMMMN+++++++++++++++++++NMNyhdmmmdhyo/-------:/oomMMMNhhhmNMMNmdhhdmNNMNmdhydMMm:''''''''''''dMM+/////////+MMh::::hMMNo.''''''''''''''.oNMMmMMd///////////////////////dMMhsssssssssssssssssyMMo    '/mMMNhssssmMMsoooooooooooooooooooooooooooooooooyMMd............+MMy-----------------/NMm/:::::::::::hMMs:::::::::::NMN++++++++++++++++++++oMMmssssdMM.
 mMNssssyMMh////////////////////hMM+:::::::::::MMm-----------+NMN+//////////sMMdoooooooooooooooooooooooooodMMdyyymMMysssssssssssyNMMMMs++++++++++omMMMms+//sMMmooooooooooooooooooyMMh::::::::::::::::::::::yMMMMNNMMdo:.'    ''-+yNMMmMMm:.............+MMh/////////+MMm////+MMh..................:mMMMMmso++///////////////////+dMMdyyyyyyyyyyyyyyyyhMMo''''''.dMMMNddhmMMhsssssssssssssssssssssssssssssssssNMN/::::::::::::dMM/:::::::::::::::::hMMs+++++++++++sMMMs///////////yMMhooooooooooooooooooooMMNssssmMM.
 mMNssssdMMy+++++++++++++++++++oNMN////////////MMM+///////////oMMd+++++++++oNMMyyyyyyyyyyyyyyyyyyyyyyyyyyhMMNddddmMMmhhhhhhhhhdmMMMMMMdssssssssyyNMMN+'    -MMdsssssssssssssssssyNMN///////////////////////sMMsNMMh:''''''''''''''.oNMMN/---------------dMMs+++++++++NMN+++++MMm-------------------/NMMmNMMNmhso+++++++++++++++syhNMMNdhhhhhhhhhhhhhhmMM:'''''''-NMMMMNNMMMmyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyNMMs/////////////mMM/:::::::::::::::::mMMyssssssssssyNMMMy++++++++++++dMMmysssssssssssssssssdMMdyyyyNMM'
 dMMyyyyhMMdsssssssssssssssssssmMMy///////////oMMMmoooooooooooomMMoooooooosNMMNmddddddddddddddddddddddddmMMMNNNNNMMMMMNNNNNNNMMNh:/mMMMmddddddmNMMMN-''''''-MMmyyyyyyyyyyyyyyyyhNMNo/////////////////////+oyMMNMMo..................+MMh::::::::::::::::+MMmooooooooomMMsooosMMd////////////////////sMMo'-/sdNMMmyooooooooooodNMMNNNMMMNmddddddddddddMMm.''''''''yMMN/:oNMMMhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhNMMyoooooooooooooohMMy/////////////////hMMmhhhhhhhhdmMMNMMdooooooooooooohMMNmhhhhhhhhhhhhhhhmMMNhhhhhMMm 
 yMMhyyyhNMMdyyyyyyyyyyyyyyyydNMMy++++++++++++sMMMMNhyyyyyyyyyyNMMssssssshNMmhmMMMMMNNNNNNNNNNNNNNNNNNNMMMMMMMNmhhMMMMNMMMNmho/.''''oNMMMMNMMNNMMMM+''''''''NMNhhhhhhhhhhhhhhhmMMMdys++++++++++++++++oydmMMMNMMMo-------------------sMMs+++++++++++++++++yMMdssssssssdMMhsssdMMy+++++++++++++++++++++MMd'''''./yNMNdssooooosmMNo.'''./smMMNNNNmmmmmNMMN:........./MMmo++yMMMNhhhhhhhhhhhhhhhhhhhhhhhhhhhhmMMNysssssssssssssssyNMNo+++++++++++++++++dMMNNNNNNNMMMmy+NMNsooooooooooooosdMMMNmmmmmmmmmmmNMMMmhhhhhdMMo 
 /MMmhhhhhNMMNmddddddddddddmNMMmsooooooooooooohMMmNMMNmdddddddNMMmyyyyyymMMh.''.:+syhdmNNMMMMMMMMMMMNNdy+-:--..'''-hMMNMMo'''''''''''-yMMMMNo--hMMm.........sMMmdddddddddddmNMMMMNNMMMdsooooooooooshNMMNho/--MMd::::::::::::::::::::yMMyoooooooooooooooooodMMdyyyyyyyhMMmhhdMMmooooooooooooooooooooooMMd........-sNMNhssssshMMs.........+NMMMMMMMMMMMd:-----------MMMmNmMmyMMNdddddddddddddddddddddddddmNMMNhhhhhhhhhhhhhhhhhhdMMNsooooooooooooooooosdmNMMMNmdhsooodMMhsssssssssssssssyhMMMMMMMMMMMMMMNmdddddddNMN. 
 'NMNddddddmNMMMMNNNNNNNMMMMNdysssssssssssssssNMMhhdmNMMMMMMMMMMmhhhhhmMMm+..................-----................../mMMN..............:hMMmooodMMs.........-dMMNNNNNNNNNNMMNy/-''''/mMNsoooooooymMMmo:'''''oMMs++++++++++++++++++++oMMmsssssssssssssssyhhhMMMmhyyyyyyMMMdNMMMNyyyyyyyyyyyyyyyyyyyyyhMMy..........:dMMhyyyymMM+----------/NMMMNhdhys/:::::::::::::NMNsMMh::yMMNdddddddddddddddddddddmmMMMMMMNmmmmmmmmmmmmmmmmmmNMMNyssssssssssssssssssssssssssssssssMMNyyyyyyyyyyyyyyyydMMy/osyhMMMNmmmmmmmmmmNMM+  
  +MMNmmmmmmmmmNNMMMMMNmddMMdyyyyyyyyyyyyyyyydMMNhhhhddmmmNNmmddhhddNMMmo-...........................................+MMy----------------:hMNNmmMM/-----------sNMMMMMMMMMMMs........./MMmsssssymMMh:.'''''''yMMyooooooooooooooooooooomMMdyyyyyyyyyyhmNMMMMNNMMMMMNmdhhNMMMMmsmMMNdhhhhhhhhhhhhhhhhhdNMN/-----------/MMNhhhhdMMy///////////sMMMy:::::::::::::::::::mMMMMd////sNMMNmmmmmmmmmmmmmmmmNNNMMNs::/hNMMMMMMMMMMMMMMMMMMMMMMMmyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyydMMNhhhhhhhhhhhhhhdMMm------sMMNNNNNNNNNNMMMs   
   yMMNNNNNNNNNNNMMN:....-NMMhyyyyyyyyyyyyyyhMMMmddddddddddddddmmNMMMd+----------------------------------------------sMMo::::::::::::::::::oMMdhMM/:::::::::::::oyhhhmMMMM+-----------MMNyyyyyNMN+..........oMMdsssssssssssssssssssssdMMMmdhhhhhhdNMMdo:.'''''-/ohMMMNmMMmo::/sdMMMNmmmmmmmmmmmmmmNMMNo::::::::::::+MMNdddddNMMsoooooooooooMMM+///////////////////NMMMMo++++++dMMMMNNNNNNNNNNNMMMMMNy/'     '-:/+oossssoooo++/oydNMMMMmhyyyyyyyyyyhdmNMMMMMMNmdhyyyyymMMNdddddddddddddMMMmyyso/::NMMMMMMMMMMMMm/    
    sMMMMMMMMMMMMMMo----:/sMMNdhhhhhhhhhhhhdNMMNNNNNNNNNNNNNNNMMMMds/:-----------------------------------------------sMMs///////////////////sMMMMM/::::::::::::::::::+MMMh///////////oMMmhhhhmMMo-----------:NMMhhhhhhhhhhhhhhhhhhhdNMMhNMMNmmmmmMMm-'''''''''''''.+mMMMMm//////+ydNMMMMMMMMMMMMMMMmy+////////////+mMMmdddddmMMNhsssssssssyMMd+++++++++++++++++++oMMMMm+++++++oohmMMMMMMMMMMMMMNhs:'''''''''''''''''''''''''''''''-/sNMMmdhhhhhhdNMMNhs+//+oymMMNdhhhhNMMMmmmmmmmmmmmMMNhddmMMMMmMMNydNMMMNmy/'     
     -yNMMMMMMMMMMMyydmNMMMMMMNdddddddddddmMMMMMMMMMMMMMMNmmNMMMMho::::::::::::::::::::::::::::::::::::::::::::::::::+MMmooo+++++++++++++++++NMMMMo///////////////////mMMyoooooooooooNMMdddddmMMs::::::::::::+NMMmmddddddddddddmmNMMNh+:/sdNMMMMMMN-''''''''''''''''.+NMMN+++++++++oosyhddmmmmddhyoo+++++++++++++yNMMNNNNNNNNNMMMNdhhhhhhhNMMhoooooooooooooooooooyMMMMmoooooooooossyddmmmmNMMh-.'''''''''''''''''''''''''''''''''''''.+dMMNNmddNMMh:'        ':hMMNdddNMMMMMNNNNNNNMMMh.  '''-/ohmMMmy/.'''         
       '-/+++/+smMMMmhyo/:--/NMMNNNNNNNNNNMMMMmMMNMMMms:.''''.:odMMm+//////////////////////////////////////////////+shMMMMMMMNNmhysoooooooooodMMMMy+++++++++++++++++++hMMhsssssssssyNMMmdddddmMMNo////////////+hNMMMMMNNNNNMMMMMMNds+//////+oyhmMMy...................:mMMsooooooooooooooossssoooooooooooooooosymMMMMMMMMMMMMMMMMMMMNNNNNMMMMysssssssssssssssssssdMMMMNsssssssssssssssyyyyNMN-'''''''''''''''''''''''''''''''''''''''''.:sdMMMNMMy'            '+MMNNNMMMNMMMMMMMMMNh:'         ''.+hNMNs-          
           -omNMms/.''       .yNMMMMMMMMMMMMMd-MMMMN+'          ':mMNo+++++++++++++++++++++++++++++++++++++++++++sdNMmho/:::/+shNMMNdysssssssdMMMMdoooooooooooooooooooyMMNdhhhhhhdmMMMNNNNNNNNNMMNy+++++++++++++oshdmmNNNNNmmdhyoo+++++++++++++yMMs--------------------/NMNyssssssyyhdddhhyyssssssssssssssssydNMMmdmNNMMMMMMMMMMMNmmNNNMNmNMMhsssssssssssssssssssmMMmMMhyyyyyyyyyyyyyyyyhNMM+..............................................:oNMMM-'''''''''''''''yMMMMMMNmMMMNysso:.'''''''''''''''''.+hMNd:        
         /hNMdo-''            '.ohmNNNNMMMMMMmshMMN:'''''''''''''':MMd+++++++++++++++++++++++++++++++++++++++++smMMy:'         ''-odMMNdyyyyymMMMMmssssssssssssssssssssMMMMNNNNNMMMMMMMMMMMMMMMMMMMmyoooooooooooooooossssssooooooooooooooooooooyMMy:::::::::::::::::::::hMMdhhhhdmNMMNmmNMMNmdhdmmNmmddhhhdNMMNmhyyyyyyhhhMMMmmmNMMMNNmdhdNMMmyyyyyyyyyyyyyyyyyyhMMMNMMMNNmddhhhhhhhhhhdNMN+................-:+osssso+:....................../MMd''''''''''''''.omMMdo:.''.+NMd.'''''''''''''''''''''''':hMMh-      
       :dMNy:'''''''''''''''''''''...+NMNy+oshNMMMh.'''''''''''''''mMNoooooooooooooooooooooooooooooooooooooooodMMh-'               '-smMMmhhhMMNNMNsssssssssssssssssssyMMNmNNNNNNmmMMMMMMMMMMMMNNmmMMNdysssssssssssssssssyyhhhhyyssssssssssssssyMMm+////////////////////sMMNddmMMNy/-.''.-/yNMMMNhhhdNMMMMMNNddhhhhhhhhhhNMM-''''.:+ydNMMMMMMMhhhhhhhhhhhhhhhdmNMMmhso+oshNMMNmmmmmmmmNMMd/-------------:+ydNNMNmmdmNMNd+--------------------/MMy.............omMNs-'''''''':NMd.''''''''''''''''''''''''./dMN+     
     .yMMh:'''''''''''''''''''''''''/NMd.    '.:yNMmo-'''''''''''''yMMysssssssssssssssssssssyhdmNNNmmdhyyssssmMMo'''''''''''''''''''''.sMMMMMMMMMMMdhyyyyyyyyyyyyyyyyydMMNdhdmNNMMMNmmmMMMdhhhhyyyyhmNMMNdhyyhddmmmddhhdNNMMMMMMNNmhyyyyyyyyhhhdNMMyooooooooooooooooooooyMMNMMMNo.''''''''''.oNMN/''../yNMMNNNNNNNNNmmmmmMMN'        './sdNMMMNdddddddddddddmMMms:.'''''''.oNMMNNNNNMMMmo:::::::::::::+hNMNds/-.''''.:yMMy::::::::/::::::::::oMMs...........:dMNs-'''''''''''oMMs..........................-yMMy'   
    -mMm+..........................-NMm.'''''''''-sNMm+............oMMdyyyyyyyyyyyyyyyyyyyydNMmhyyyyhmNMNNdhmMM+'''''''''''''''''''''-yNMmyo///+sdNMNmdhhhhhhhhhhhhhhhNMMMMMMNdyo:-.'''-NMNhhhhhhhhhhdmNMMMNNMMNdddNMMMMds/--.-/sdMMNmdddmmNNMMNmmMMysssssssssssssssssssNMNyMMd:'''''''''''''':dMN+....-sMMMMNmdddmNMMMMMMMM-'''''''''''''-+hNMMNmmmmmmmmmmMMNo-''''''''''''-dMMMMMNmho/:::::::::::/omMMh+-''''''''''''hMMyhdmmNNNNNNNmmdhysohMM+----------+NMm/..............mMN-..........................-oMMy   
   :NMd:...........................hMM:''''''''''''-hMMy-----------+MMmyyhhhhhddddddhhhhhymMMo.'    ''.:sdNMMMy'''''''''''''''''''''/NMm+.''''''''-+dMMNdddddddddddddNMMMNds/.'         mMMmmmmmmmNNNmmmNMMNho-...-dMMy:''''''''''-yNMMMMNmhy+:-.-mMNhyyyyyyyyyyyyyyyyymMMhNMm-................-dMM+-/ymMNh+:..'''..-/ymMMMM+''''''''''''''''-+hNMMMNNNNNMMMm:...............:NMMso++/////////////+dMMh:.''''''''''''''/MMNdhysoo+++oosyhdmNMMMMdo+:::::::+NMm:---------------sMM+----------------------------sMMs  
  -NMd:---------------------------:MMd..............-sMMh:---------+MMNNNNMMMMNNNNNNMMMMNNMMy'''''''''''''-omMNy-................../NMd-''''''''''''.+mMMNmmmmmmmmNNMMNh+-'''''''''''''.MMMMMMMMNmmmmNMMMMMs-....:mMm/.'''''''''''''/mMMs:-.......:dMMmhhhhhhhhhhhhhhdNMNyhMM+------------------/NMNsNMmo-'''''''''''''.+mMMh.'''''''''''''''''.:smMMMMMMMMN/-----------------yMMs+++++++++++++++oNMN+................./MMs''           ''..-/shmMNmho/::/mMN/----------------oMMs----------------------------:hMM: 
 'mMN/----------------------------+MMs----------------sMMy:::::/oydNMNmdys+/:--....--:/+sdMM+'''''''''''''''-oNMm+................-mMN:...............:dMMMNNNNMMMMNh+-''''''''''''''''/MMMMNho:-.....-/sdNMms:-/NMm:................:mMN/---------:yNMNmmmmmmmmmmmmNMMMh+NMN/:::::::::::::::::::yMMMMh:.................-hMMs....................-omMMmsMMh//////////////////sMMyoooooooooooooooNMN/------------------sMM/'''''''''''''''''''''.:odNMmy+yMMy:::::::::::::::::yMMs:::::::::::::::::::::::::::::/NMd 
 sMMo:::::::::::::::::::::::::::::oMMs:::::::::::::::::dMMo//ohNMNds/-.''''''''''''''''''+MM+.................:dMNo---------------+MMy:::::::::::::::::/NMMMMMMMMms:.'''''''''''''''''.yMMNo-'''''''''''''-sNMmomMN/------------------+MMh///////////+hNMMMMNNNNMMMMNdMMmsNMN++++++++++++++++++++oMMMd:--------------------hMM+---------------------:sNMNMMh++++++++++++++++++dMMyoooooooooooooodMMs:::::::::::::::::::mMN-''''''''''''''''''''''''.:sNMNNMM+/////////////////dMM+//////////////////////////////hMM:
.NMd//////////////////////////////oMMh/////////////////oMMdsmMNh+-.'''''''''''''''''''''':MMy------------------:mMN/--------------oMMy//////////////////hMMsdMMmo-....................oNMd:.................:dMMMMh::::::::::::::::::::NMN+++++++++++++osdmNNNNNmmhso+mMMymMMyooooooooooooooooooosMMM+:::::::::::::::::::::/NMm:----------------------/hMMMmoooooooooooooooooyMMNsssssssssssssssNMN///////////////////sMMy............................:hMMMN+++++++++++++++++oMMm+//////////////////////////////oMMy
oMMs///////////////////////////////NMN++++++++++++++++++NMMMMy:...........................mMN/::::::::::::::::::oMMh::::::::::::::+MMd++++++++++++++++++hMMNMmo----------------------+MMd:-------------------:dMMMs////////////////////NMNooooooooooooooooossssssooooomMMdmMMNyssssssssssssssssssdMMN+++++++++++++++++++++++hMM+::::::::::::::::::::::::sNMMdyyyyyyyyyyyyyyyhNMNhyyyyyyyyyyyyyyyMMm++++++++++++++++++oNMm:-----------------------------:mMMNsoooooooooooooooodMMy++++++++++++++++++++++++++++++++NMd
dMM++++++++++++++++++++++++++++++++dMMyoooooooooooooooooNMMMo-............................oMMh///////////////////NMN///////////////dMMhsssssssssssssssssmMMMh/----------------------:mMN/:::::::::::::::::::::+MMMsooooooooooooooooooosMMmyyyyyyyyyyyyyyyyyyyyyyyyyyyyMMMMNmNMNhyyyyyyyyyyyyyyyydMMMMsoooooooooooooooooooooohMMs/////////////////////////omMMmdhhhhhhhhhhhhmMMNhhhhhhhhhhhhhhhhhMMNooooooooooooooooosNMN+:::::::::::::::::::::::::::::::dMMMhyyyyyyyyyyyyyyyyMMNoooooooooooooooooooooooooooooooooNMN
NMN++++++++++++++++++++++++++++++++sMMmssssssssssssssssyMMMd------------------------------:hMMy++++++++++++++++++mMM///////////////+mMMdyyyyyyyyyyyyyyydMMNo::::::::::::::::::::::::+MMd///////////////////////NMMdsssssssssssssssssssNMMdhhhhhhhhhhhhhhhhhhhhhhhhhhdNMNo/-.-hMMmddhhhhhhhhhhhdmMMhmMNhsssssssssssssssssssssmMMo//////////////////////////oNMMMNmmmmmmmmmNMMMNdhhhhhhhhhhhhhhhhhNMMyssssssssssssssshNMNo///////////////////////////////sMMMMNhhhhhhhhhhhhhhhNMMyoooooooooooooooooooooooooooooooooNMN
NMNooooooooooooooooooooooooooooooooodMMdyyyyyyyyyyyyyyymMMMm/::::::::::::::::::::::::::::::/mMMhsooooooooooooooosNMN++++++++++++++++odMMmdhhhhhhhhhhhdNMMm+/////////////////////////sMMhoooooooooooooooooooooosMMMMhyyyyyyyyyyyyyyyyhNMMMMNNNmmmmmmmmmmmmmmmmmmmmmmNMMd-     '+mMMNmmmmmmmmmmNMMm+'-hMMmhhhhhhhhhhhhhhhhhhhdMMm++++++++++++++++++++++++++++sMMMNMMMMMMMMMNdyNMNNmdddddddddddddddmMMmyyyyyyyyyyyyyhmMMmo++++++++++++++++++++++++++++++ohMMNdNMMmddddddddddddNMMNysssssssssssssssssssssssssssssssssMMd
mMNssssssssssssssssssssssssssssssssssNMMdhhhhhhhhhhhhhmMMNMMd+//////////////////////////////+mMMdyyyyyyyyyyyyyyyhMMdooooooooooooooooooyNMMNmmmmmmmmmNMMMm+//////////////////////////oMMdsssssssssssssssssssssyNMNmMMdhhhhhhhhhhhhhhmNMm/:+shmmNNMMMMMMMMMMMMMMMMMMNmy:'        '/ymNMMMMMMMMMNh+.   '/dNMNmmddddddddddddddmMMNsooooooooooooooooooooooooooooohMMo:oyhhhyo/.  -omNMMNNNmmmmmmmmmmmmNMMmdddddddddddmNMNhoooooooooooooooooooooooooooooosymMMmhhdNMMNNmmmmmmmmmMMmNMNhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhMMo
yMMyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyydMMMMmddddddddddmNMMmhmMMmso+++++++++++++++++++++++++++++odMMNdhhhhhhhhhhhhhNMMsoooooooooooooooooooshmNMMMMMMMMNNMMNo++++++++++++++++++++++++++++mMMhhhhhhhhhhhhhhhhhhhhmMMd-'yNMNmmmmmmmmmmmNNMNs.      '-:/+osyhhhddddhhys+:-'              ':+syhhys+:.         -odNNMMNNNNNNNNNNMMMNdssssssssssssssssssssssssssssssssMMy              ':odmNMMMMMMMMMMMMMMMMMNmmmmmmmmNMMNmysssssssssssssssssssssssssssssydNMMNmdddddmNMMMMMMMMMMMNy..hMMmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhNMN.
:MMmyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhNMNosNMMNNNNNNNNMMMNdddddNMMmysoooooooooooooooooooooooooooooyNMMNmddddddddddNMMhssssssssssssssssssssssssyhdmmMMN-oMMhooooooooooooooooooooooooooooosNMMmdddddddddddddddmNMMmo'   -smNMMMMMMMMMMNmo.                                                                     .:+shdmmNNNmmddMMhssssssssssssssssssssssssssssssssyMMd                  '-/oydmNNNNMMMMMMMMMMMMMMMMMMNdhyyyyyyyyyyyyyyyyyyyyyyyyyyyyhdmMMmmMMNmmmmmmmNMMhdmmmdy+.   'oNMNmdhhhhhhhhhhhhhhhhhhhhhhhhhhmMMo 
 dMMdhhhhhhhhhhhhhhhhhhhhhhhhhhhhmMMm:  -smNMMMMMMMMNmddddddmNMMMNdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhNMMMNNNmmmNNMMNhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhMMs dMMssssssssssssssssssssssssssssssssdMMMNNNNNNNNNNNMMMNms:'       ':+yhmmmmhs+-                                                                              '''..'' .NMNhyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhMMh                        ''.-::://////yMMMMMNNmdhhhhhhhhhhhhhhhhhhhhhhhhhhdddmNMNmy:'.yNMMNNNNNMMM+  '''         .sNMNmddddddddddddddddddddddddmMMh  
 -NMNddddddddddddddddddddddddddmMMNo'     '-/+o+/:mMMNNNNNNNMMNssmMMNdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdmNMMMMMMMMMMdyyyyyyyyyyyyyyyyyyyyyyyyyyyyyymMM- NMNsssssssssssssssssssssssssssssssssdMMmmNNNNNNNmdyo/.                                                                                                               -mMNdhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhmMM:                                      /dNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmNNMMNdo:'     -yNMMMMMMm/                 .omMMNNmmmmmmmmmmmmmmmmmmmmNMMy'  
  :NMMmddddddddddddddddddddmmNMMmo.               -mMMMMMMMMNh-  ':smNMNNmdddddddddddddddddddddddddddddmNNMMMNhMMmhhhhhhhhhhhhhhhhhhhhhhhhhhhhdMMy  dMMyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyhNMm' '.....'                                                                                                                      .yMMNddddddddddddddddddddddddddddmMMs                                         -odNNMMMMNNNNNNNNNNNNNNNNNMMMMNNmyo:'           ./oyys/'                    ':ymNMMMNNNNNNNNNNNNNNNNMMm/    
   .dMMNNNNNNNNNNNNNNNNNNNNMMNh/'                  'omNMNNms-        -+ymNMMNNNmmmmmmmmmmmmmmmmmmmmmmmNNNMMmo. +NMMmddddddddddddddddddddddddddMMm'  /MMmhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhdMMm-                                                                                                                                 :dMMNmmmmmmmmmmmmmmmmmmmmmmmmmMMNo                                             '-/oydmNNNNNMMMMMNNNNNmhyo/-.                                               ':ohNNMMMMMMMMMMMMMMNd+'     
     /dMMMMMMMMMMMMMMMMMMNmy/'                        .--.               ./ohmNMMMMMMMMMMMMMMMMMMMMMMMNmho-     'sNMMmddddddddddddddddddddddmMMm.    yMMmddddddddddddddddddddddddddddNMMy'                                                                                                                                    -yNMMMNNNNNNNNNNNNNNNNNNNMMMNs.                                                      '..--::::--.'                                                            -/oshdmNNNmdho/.        
       -ohNMMMMMMMMMNmhs/.                                                    '-:+oyhddmNNNNNmddhys+/-.           .oNMMNNmmmmmmmmmmmmmmmmmmNMMh'      oNMMmmmmmmmmmmmmmmmmmmmmmmmmmNMMh-                                                                                                                                        ':smNMMMMMMMMMMMMMMMMMNmy/'                                                                                                                                                         
           .-:///:-.'                                                                                               '/hNMMMNNNNNNNNNNNNNNMMMm+         .sNMMMNNNNNNNNNNNNNNNNNNNMMMNs-                                                                                                                                              .:+shdNNNMNNmdhs+:.                                                                                                                                                             
                                                                                                                       '/smMMMMMMMMMMMMMMMh/'            '/smMMMMMMMMMMMMMMMMMMMds:                                                                                                                                                          '                                                                                                                                                                      
                                                                                                                           ':+syddmmmdyo:'                   ':+shdmNMMMNmdhs+:'                                                                                                                                                                                                                                                                                                                                    
        
                `}
            </pre>
        </div>
    )
}

export default Floor;